---
title: "The TimeFRAME Package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The TimeFRAME Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

set.seed(1)
```

```{r setup}
library(TimeFRAME)
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)

# Time series parameters
N <- 64
eta <- 5
t <- seq(0, 2, length.out = N)
n2o_labels <- c(d15N = bquote(delta^15 * "N"), d15NSP = bquote(delta^15 * "N" ^ "SP"))

# Fix source contributions and fractionation weight
d.weights <- data.frame(t = t) %>%
  mutate(f1 = 0.5 + cos(4*t)/(1+t)) %>%
  mutate(f1 = exp(f1)/(1+exp(f1)), f2 = 1-f1) %>%
  mutate(r1 = 0.1 + 0.1 * t) %>%
  rename(Ni = f1, bD = f2, Red = r1)

# Create model class
sources <- n2o_sources[1:2,c(1,2,4,5)]  # only 2 sources with 2 measurements
frac <- n2o_frac[,c(1,2,4,5)]  # only 2 measurements
model <- frame_model(sources, frac = frac)

d.weights %>%
  pivot_longer(-t, names_to = "source") %>%
  mutate(source = factor(source, levels = names(d.weights)[2:4])) %>%
  ggplot() +
  geom_line(aes(x = t, y = value, col = source), linewidth = 1) +
  ylim(0, 1) +
  facet_grid(source ~ .) +
  xlab("Source") + ylab("Source Contribution and Fractionation Weight") +
  labs(col = "Time", title = "Fixed Values for f and r") +
  theme_bw()
```


```{r}
# Compute measurement means
d.mean <- param_map(model, d.weights[,-1]) %>% 
  as.data.frame() %>%
  add_column(t = d.weights$t, .before = 1)

# Simulate measurements
d.meas <- sample_measurements(model, d.weights[,-1], eta) %>% 
  as.data.frame() %>%
  add_column(t = d.weights$t, .before = 1)

autoplot(model, d.meas[,2:3])
```


```{r}
# Plot means and sampled measurements
d.mean %>%
  pivot_longer(c(d15N, d15NSP), names_to = "variable", values_to = "mean") %>%
  inner_join(d.meas %>%
               pivot_longer(c(d15N, d15NSP), names_to = "variable"),
             by = c("t", "variable")) %>%
  mutate(variable = factor(variable, labels = n2o_labels)) %>%
  ggplot() +
  geom_line(aes(x = t, y = mean)) +
  geom_point(aes(x = t, y = mean), shape = 1) +
  geom_point(aes(x = t, y = value), col = "steelblue") +
  geom_linerange(aes(x = t, ymin = value, ymax = mean), col = "steelblue", alpha = 0.6) +
  geom_smooth(aes(x = t, y = value), col = "steelblue", fill = "steelblue") +
  facet_grid(variable ~ ., scales = "free_y", labeller = label_parsed) +
  xlab("Time") + ylab("Isotopic Measurement") +
  theme_bw()
```



# Stationary Inference

```{r}
meas <- d.meas[,2:3]
isotope_map(model, colMeans(meas))
```


```{r, warning = FALSE}
system.time({ fit <- fit_stationary(model, meas, eta = eta) })
```


```{r}
coef(fit)
```


```{r}
as.data.frame(fit)
```


```{r}
autoplot(fit)
```



# Time Series Inference

```{r}
isotope_map(model, meas) %>%
  as.data.frame() %>%
  add_column(t = t) %>%
  pivot_longer(-t, names_to = "variable", values_to = "pred") %>%
  inner_join(d.weights %>%
               pivot_longer(-t, names_to = "variable"),
             by = c("t", "variable")) %>%
  ggplot() +
  geom_line(aes(x = t, y = value, group = variable), linewidth = 1, col = "gray80") +
  geom_line(aes(x = t, y = pred, col = variable), linewidth = 1) +
  ylim(0, 1) +
  facet_grid(variable ~ .) +
  xlab("Time") + ylab("Source Contribution and Fractionation Weight") + 
  labs(col = "Source", title = "Isotope Mapping") +
  theme_bw()
```


## Independent FRAME Model

```{r}
system.time({ fit.frame <- fit_frame(model, meas, t = t, eta = eta) })
```


```{r}
coef(fit.frame)
```



```{r}
autoplot(fit.frame)
```



## Spline GLM Model

```{r}
system.time({ fit.glm <- fit_glm(model, meas, t = t, eta = eta) })
```


```{r}
autoplot(fit.glm)
```



## Gaussian Process Model

```{r}
system.time({ fit.gp <- fit_gp(model, meas, t = t, eta = eta, iter = 2000, cores = 4, chains = 4) })
```


```{r}
autoplot(fit.gp)
```



## Dirichlet-Gaussian Process Model

```{r}
system.time({ fit.dgp <- fit_dgp(model, meas, t = t, eta = eta, iter = 2000, cores = 4, chains = 4) })
```


```{r}
autoplot(fit.dgp)
```



## Hierarchical Dirichlet-Gaussian Process Model

```{r}
system.time({ fit.hdgp <- fit_dgp(model, meas, t = t, eta = eta, estim.rho = TRUE, iter = 2000, cores = 4, chains = 4) })
```


```{r}
autoplot(fit.hdgp)
```





