// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4dgp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4frame_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gp2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4hdgp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4spline_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4stationary_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4dgp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dgp_mod, 0},
    {"_rcpp_module_boot_stan_fit4frame_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4frame_mod, 0},
    {"_rcpp_module_boot_stan_fit4gp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gp_mod, 0},
    {"_rcpp_module_boot_stan_fit4gp2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gp2_mod, 0},
    {"_rcpp_module_boot_stan_fit4hdgp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4hdgp_mod, 0},
    {"_rcpp_module_boot_stan_fit4spline_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4spline_mod, 0},
    {"_rcpp_module_boot_stan_fit4stationary_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4stationary_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_TimeFRAME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
